version: version.c 
	gcc -o version version.c -lsqlite3 -std=c99

version2: version.c 
	gcc -o version version.c -lsqlite3 
vs:  version_select.c 
	gcc -o version_select version_select.c -lsqlite3 
insert_data:  insert_data.c 
	gcc -o insert_data insert_data.c -lsqlite3 
